#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get -y update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Using sed to do a 301 Redirection
Updated_Rule="server_name _;\\n\\trewrite ^/redirect_me https://github.com/Kakazablone permanent;"
if ! grep -q "rewrite ^/redirect_me https://github.com/Kakazablone permanent;" /etc/nginx/sites-enabled/default; then
    sudo sed -i "s#server_name _;#$Updated_Rule#" /etc/nginx/sites-enabled/default
fi

# Custom 404 page that contains the string Ceci n'est pas une page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Using sed to add the 404 page configuration if it doesn't already exist
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-enabled/default; then
    Updated_Rule="listen 80 default_server;\\n\terror_page 404 /404.html;\\n\\tlocation = /404.html {\\n\\t\\tinternal;\\n\\t}"
    sudo sed -i "s#listen 80 default_server;#$Updated_Rule#" /etc/nginx/sites-enabled/default
fi

# Restarting Nginx service
sudo service nginx restart
