#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

# Update package information
sudo apt-get -y update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx service
sudo systemctl start nginx

if ! grep -q "add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default; then
# Configuring Custon Nginx header
sudo sed -i '/server_name _;/a'\
        'add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default
fi

sudo systemctl restart nginx
