#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt -y update
sudo apt -y install haproxy

#Making sure that HAproxy can be managed via an init script
sudo systemctl start haproxy
sudo systemctl enable haproxy

# Define your configurations
configurations="
frontend load_balancer
    bind *:80
    mode http
    default_backend app_servers

backend app_servers
    server 420276-web-01 100.25.102.191:80
    server 420276-web-02 100.26.161.26:80
"

# Append configurations to haproxy.cfg
echo "$configurations" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
